### PR TITLE
r113 compatibility update

### PR DESCRIPTION
**Pull request by geoff-harper**

### CODE REVIEW

**Comment by pjurczynski** [comment]
why do you need the "build"?

**Comment by rhuitl** [comment]
I think this can be closed, https://github.com/pnext/three-loader/pull/58 has been merged instead.

**Comment by pjurczynski** [comment]
thanks!

**Comment by geoff-harper** [comment]
@pjurczynski Sorry I had intended to push it on a fork for testing but got mixed up

**Pull request closed without merging**
